from pydantic import BaseModel, Field
from typing import Optional, Literal
from datetime import datetime, date
from uuid import UUID, uuid4
import hashlib


class Message(BaseModel):
    role: Literal["user", "assistant", "system", "agent"]
    content: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    agent_name: Optional[str] = None

    def to_llm_dict(self) -> dict:
        role = "assistant" if self.role == "agent" else self.role
        return {"role": role, "content": self.content}


class Session(BaseModel):
    id: UUID = Field(default_factory=uuid4)
    user_id: str
    messages: list[Message] = Field(default_factory=list)
    active_agents: list[str] = Field(default_factory=list)
    metadata: dict = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    closed_at: Optional[datetime] = None


class Paper(BaseModel):
    title: str
    abstract: str = ""
    authors: list[str] = Field(default_factory=list)
    year: Optional[int] = None
    source: Literal["arxiv", "semantic_scholar", "unknown"] = "unknown"
    url: str = ""
    doi: Optional[str] = None
    citation_count: int = 0

    def content_hash(self) -> str:
        key = self.doi if self.doi else self.title.lower().strip()
        return hashlib.sha256(key.encode()).hexdigest()[:16]

    def to_context_str(self) -> str:
        authors_str = ", ".join(self.authors[:3]) + (" et al." if len(self.authors) > 3 else "")
        return (
            f"**{self.title}** ({self.year or '?'}) — {authors_str}\n"
            f"{self.abstract[:300]}...\n[{self.source}] {self.url}"
        )


class ChunkMetadata(BaseModel):
    type: Literal["research", "dataset", "devlog", "manual"]
    agent: str
    topic: str = ""
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    source_entry_id: Optional[str] = None
    chunk_index: int = 0


class KnowledgeEntry(BaseModel):
    id: Optional[UUID] = None
    user_id: str
    agent: Literal["research", "dataset", "manual"]
    title: str
    content: str
    summary: Optional[str] = None
    source_url: Optional[str] = None
    tags: list[str] = Field(default_factory=list)
    metadata: ChunkMetadata = Field(default_factory=lambda: ChunkMetadata(type="manual", agent="manual"))
    content_hash: Optional[str] = None
    session_id: Optional[UUID] = None
    created_at: Optional[datetime] = None


class KnowledgeSearchResult(BaseModel):
    entry: KnowledgeEntry
    similarity: float
    recency_score: float = 0.0
    hybrid_score: float = 0.0


class Dataset(BaseModel):
    name: str
    source: Literal["huggingface", "kaggle", "other"] = "other"
    url: str = ""
    huggingface_id: Optional[str] = None
    size: str = "unknown"
    format: str = "unknown"
    downloads: int = 0
    likes: int = 0
    relevance_score: float = 0.0
    ranking_score: float = 0.0
    relevance_reason: str = ""
    limitations: str = ""


class Task(BaseModel):
    task: str
    status: Literal["done", "in_progress", "blocked", "planned"] = "done"
    notes: Optional[str] = None


class CommitMetadata(BaseModel):
    commit_sha: str
    summary: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    branch: str = "jarvis/devlog"
    repo: str = ""
    url: str = ""


class Devlog(BaseModel):
    id: Optional[UUID] = None
    user_id: str
    date: date
    summary: str
    tasks: list[Task] = Field(default_factory=list)
    commits: list[str] = Field(default_factory=list)
    commit_metadata: list[CommitMetadata] = Field(default_factory=list)
    topics: list[str] = Field(default_factory=list)
    mood: Optional[int] = Field(None, ge=1, le=5)
    github_path: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

    def to_markdown(self) -> str:
        lines = [f"# Dev Log — {self.date.strftime('%B %d, %Y')}", "", "## Summary", self.summary, ""]
        if self.tasks:
            lines += ["## Tasks", ""]
            icons = {"done": "✅", "in_progress": "🔄", "blocked": "🚫", "planned": "📋"}
            for t in self.tasks:
                note = f" — {t.notes}" if t.notes else ""
                lines.append(f"- {icons.get(t.status, '•')} {t.task}{note}")
            lines.append("")
        if self.topics:
            lines += ["## Topics", ", ".join(self.topics), ""]
        if self.commits:
            lines += ["## Commits", ""]
            for sha in self.commits:
                lines.append(f"- `{sha}`")
            lines.append("")
        if self.mood:
            lines += [f"## Mood", f"{'⭐' * self.mood} ({self.mood}/5)", ""]
        lines += ["---", f"*Generated by Jarvis on {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}*"]
        return "\n".join(lines)


class ToneProfile(BaseModel):
    tone: Literal["builder", "technical", "casual", "professional"] = "builder"
    length: Literal["short", "medium", "long"] = "medium"
    audience: Literal["tech", "general", "founders"] = "tech"
    avoid_phrases: list[str] = Field(default_factory=list)


class LinkedInPost(BaseModel):
    id: Optional[UUID] = None
    user_id: str
    content: str
    hook: str = ""
    hashtags: list[str] = Field(default_factory=list)
    word_count: int = 0
    status: Literal["draft", "approved", "posted"] = "draft"
    source_devlog_ids: list[str] = Field(default_factory=list)
    tone_profile: Optional[ToneProfile] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    approved_at: Optional[datetime] = None
    posted_at: Optional[datetime] = None


class AgentRun(BaseModel):
    id: Optional[UUID] = None
    session_id: str
    user_id: str
    agent_name: str
    intent: str
    status: Literal["running", "success", "failed", "timeout"] = "running"
    model_used: Optional[str] = None
    error: Optional[str] = None
    duration_ms: Optional[int] = None
    started_at: datetime = Field(default_factory=datetime.utcnow)
    completed_at: Optional[datetime] = None
